### ISSUE TITLE
Update All Packages Related with Asp.net 2.1

### ISSUE THREAD

**Issue by tuliorezende** [lfmundim/Blip.Api.Template#2]
Hi Mundim!

As we talked earlier today, we need all packages related with Asp.Net core updated.

Some packages in generated projects are in version 2.0.

I Attach an example of some things you need to change.

Output XML files (Change direct to "netcoreapp2.1")
Package Microsoft.AspNetCore.All
Package Microsoft.VisualStudio.Web.CodeGeneration.Design

![examples](https://user-images.githubusercontent.com/6129653/50607099-3d2dfb00-0eaf-11e9-84d7-58d13b365c67.PNG)

Regards!

Túlio

**Comment by lfmundim** [comment]
Source code updated (: Template should be available in the next few hours
